"""Deterministic paraphraser for the Stage 1.5 stress harness (plan §6 Stage 1.5).

Rewrites the surface form of every message the simulated customer can produce,
without any network or LLM call at runtime. Two levels:

- L1 "framing": the sentence frame changes, but constraint payloads and the
  "; " joiner stay byte-identical. Models a conservative private evaluator.
- L2 "aggressive": frame changes plus payload mutations — joiner replacement,
  first-letter case flips, budget rephrasing, constraint reordering. Models the
  private-set worst case.

Determinism: every rewrite is drawn from a `random.Random` seeded from
(global seed, sample_id, turn, level), so a run is exactly reproducible.

Cache replay: if `data/paraphrase_cache.jsonl` exists, its rewrites take
priority over templates. Each line is `{"original": "<exact message>",
"rewrite": "<replacement>"}`. To populate it with LLM paraphrases: collect the
distinct messages of a run (they are fully enumerable from the public set),
send each to a model offline, and write the pairs — the harness then replays
them with no network, satisfying §9's offline final-verification constraint.
"""
from __future__ import annotations

import json
import random
import re
from pathlib import Path


# Message shapes generated by evaluator.local_evaluator. Order matters: the
# intent_override opening ("I'm looking for {cat}. {old}") is a catch-all for
# "I'm looking for" messages and must be matched last.
SHAPES: list[tuple[str, re.Pattern]] = [
    ("exploring", re.compile(r"^I'm looking for (?P<cat>.+?), but I'm still exploring\.$")),
    ("key_requirement", re.compile(r"^I'm looking for (?P<cat>.+?)\. A key requirement is: (?P<constraint>.+)\.$")),
    ("override", re.compile(r"^Actually, ignore my earlier preference\. What I need is: (?P<constraint>.+)\.$")),
    ("reply", re.compile(r"^For that, what matters is: (?P<payload>.+)\.$")),
    ("boundary", re.compile(r"^I don't have a preference for (?P<attr>.+); please use your judgment\.$")),
    ("no_additional", re.compile(r"^I don't have an additional preference for (?P<attr>.+)\.$")),
    ("dissatisfied", re.compile(r"^Those options are not quite right yet\. Ask me about one specific attribute\.$")),
    ("override_old", re.compile(r"^I'm looking for (?P<cat>.+?)\. (?P<old>.+)$")),
]

L1_TEMPLATES: dict[str, list[str]] = {
    "exploring": [
        "I want to find {cat}, though I'm still exploring my options.",
        "Help me track down {cat} — just browsing for now.",
        "I'm in the market for {cat}, but still weighing what's out there.",
        "Could you show me {cat}? I'm still exploring.",
    ],
    "key_requirement": [
        "I want to find {cat}. One thing I definitely need: {constraint}.",
        "Help me track down {cat}. A must-have for me is: {constraint}.",
        "I'm in the market for {cat}, and a key requirement is: {constraint}.",
        "Looking to buy {cat} — the main thing is: {constraint}.",
    ],
    "override": [
        "On second thought, forget what I said earlier. What I need is: {constraint}.",
        "Change of plans — please ignore my previous preference. What I need is: {constraint}.",
        "Scratch my earlier preference. Here's what I actually need: {constraint}.",
        "Never mind what I said before; what I need is: {constraint}.",
    ],
    "reply": [
        "What matters to me is: {payload}.",
        "Here's what I care about: {payload}.",
        "For that one, I'd prioritize: {payload}.",
        "The important things are: {payload}.",
    ],
    "boundary": [
        "No real preference for {attr} — please use your judgment.",
        "I'm easy on {attr}; use your judgment.",
        "Whatever you think on {attr} — your judgment is fine.",
    ],
    "no_additional": [
        "Nothing more to add on {attr} — no additional preference there.",
        "I don't have any additional preference for {attr}.",
        "No additional preference on {attr} from me.",
    ],
    "dissatisfied": [
        "Those aren't quite it yet. Ask me about one specific attribute.",
        "Not quite what I'm after yet — ask me about one specific attribute.",
        "Hmm, those options are not quite right. Ask me about one specific attribute, please.",
    ],
    "override_old": [
        "I want to find {cat}. {old}",
        "Help me track down {cat}. {old}",
        "I'm in the market for {cat}. {old}",
    ],
}

# Extra frames only L2 draws from (reworded "looking for" etc.).
L2_EXTRA_TEMPLATES: dict[str, list[str]] = {
    "exploring": [
        "I'm shopping for {cat} but haven't settled on anything.",
        "I'm after {cat}; still just having a look around.",
    ],
    "key_requirement": [
        "I'm shopping for {cat} and it absolutely has to have: {constraint}.",
        "I'm after {cat} — non-negotiable: {constraint}.",
    ],
    "override": [
        "Actually, drop that. The thing I need now: {constraint}.",
    ],
    "reply": [
        "Priorities for that: {payload}.",
    ],
    "override_old": [
        "I'm shopping for {cat}. {old}",
        "I'm after {cat}. {old}",
    ],
}

L2_JOINERS = ["; ", " and also ", ", plus "]
BUDGET_CONSTRAINT_RE = re.compile(r"^budget around \$(?P<amt>\d[\d,]*\.?\d*)$", re.IGNORECASE)
BUDGET_VARIANTS = [
    "my budget's about {amt} dollars",
    "somewhere around ${amt} works for me",
    "I can spend around ${amt}",
    "roughly ${amt} is my budget",
]


def _flip_first_letter(value: str) -> str:
    if value and value[0].isalpha():
        first = value[0].lower() if value[0].isupper() else value[0].upper()
        return first + value[1:]
    return value


class Paraphraser:
    def __init__(
        self,
        level: str = "L1",
        seed: int = 0,
        cache_path: str | Path = "data/paraphrase_cache.jsonl",
    ) -> None:
        if level not in {"none", "L1", "L2"}:
            raise ValueError(f"unknown level: {level}")
        self.level = level
        self.seed = seed
        self.cache: dict[str, str] = {}
        cache_file = Path(cache_path)
        if cache_file.exists():
            with cache_file.open(encoding="utf-8") as handle:
                for line in handle:
                    if line.strip():
                        entry = json.loads(line)
                        self.cache[str(entry["original"])] = str(entry["rewrite"])

    def paraphrase(self, message: str, sample_id: str, turn: int) -> str:
        if self.level == "none":
            return message
        if message in self.cache:
            return self.cache[message]
        for shape, pattern in SHAPES:
            match = pattern.match(message)
            if match:
                rng = random.Random(f"{self.seed}\0{sample_id}\0{turn}\0{self.level}")
                return self._render(shape, match.groupdict(), rng)
        return message  # unrecognized shape: leave untouched

    def _render(self, shape: str, groups: dict[str, str], rng: random.Random) -> str:
        templates = list(L1_TEMPLATES[shape])
        if self.level == "L2":
            templates += L2_EXTRA_TEMPLATES.get(shape, [])
            groups = {key: self._mutate_payload(shape, key, value, rng) for key, value in groups.items()}
        return rng.choice(templates).format(**groups)

    def _mutate_payload(self, shape: str, key: str, value: str, rng: random.Random) -> str:
        if key in {"cat", "attr", "old"}:
            return value
        if key == "payload":  # "; "-joined constraint list from customer_reply
            constraints = value.split("; ")
            constraints = [self._mutate_constraint(item, rng) for item in constraints]
            if len(constraints) >= 2 and rng.random() < 0.5:
                rng.shuffle(constraints)
            return rng.choice(L2_JOINERS).join(constraints)
        if key == "constraint":
            return self._mutate_constraint(value, rng)
        return value

    def _mutate_constraint(self, value: str, rng: random.Random) -> str:
        budget = BUDGET_CONSTRAINT_RE.match(value)
        if budget:
            return rng.choice(BUDGET_VARIANTS).format(amt=budget.group("amt"))
        if rng.random() < 0.5:
            return _flip_first_letter(value)
        return value
